version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1381
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_data_directory:/var/lib/mysql-files/
      - ./mysql/conf.d:/etc/mysql/conf.d # Mount MySQL config directory
    networks:
      backend:
        ipv4_address: 172.28.0.2

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_conf:/etc/clickhouse-server # Mount ClickHouse config directory
    networks:
      backend:
        ipv4_address: 172.28.0.3

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  mysql_data:
  clickhouse_data:
  mysql_conf: # MySQL config volume
  clickhouse_conf: # ClickHouse config volume
